<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnggaranSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // RO Z06
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => 'Z06',
                'kode_subkomponen' => null,
                'kode_akun' => null,
                'program_kegiatan' => 'Rencana Kebutuhan BMN dan Pengelolaannya',
                'pic' => 'SJ.7',
                'pagu_anggaran' => 572012000,
                'referensi' => '4753EBAZ06',
                'referensi2' => '4753EBAZ06',
                'ref_output' => '4753EBAZ06',
                'len' => 10,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => 'Z06',
                'kode_subkomponen' => 'AA',
                'kode_akun' => null,
                'program_kegiatan' => 'Koordinasi pemenuhan kebutuhan gedung kantor dan hunian pegawai kemenkeu',
                'pic' => '7',
                'pagu_anggaran' => 65499000,
                'referensi' => '4753EBAZ06AAAA',
                'referensi2' => '4753EBAZ06AA',
                'ref_output' => '4753EBAZ06',
                'len' => 14,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => 'Z06',
                'kode_subkomponen' => 'AA',
                'kode_akun' => '521211',
                'program_kegiatan' => 'Belanja bahan',
                'pic' => '714',
                'pagu_anggaran' => 4313000,
                'referensi' => '4753EBAZ06AA521211',
                'referensi2' => '4753EBAZ06AA',
                'ref_output' => '4753EBAZ06',
                'len' => 18,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => 'Z06',
                'kode_subkomponen' => 'AA',
                'kode_akun' => '524111',
                'program_kegiatan' => 'Belanja perjalanan biasa',
                'pic' => '714',
                'pagu_anggaran' => 61186000,
                'referensi' => '4753EBAZ06AA524111',
                'referensi2' => '4753EBAZ06AA',
                'ref_output' => '4753EBAZ06',
                'len' => 18,
            ],

            // RO 403
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '403',
                'kode_subkomponen' => null,
                'kode_akun' => null,
                'program_kegiatan' => 'Layanan Pengadaan',
                'pic' => 'SJ.7',
                'pagu_anggaran' => 39265000,
                'referensi' => '4753EBA403',
                'referensi2' => '4753EBA403',
                'ref_output' => '4753EBA403',
                'len' => 10,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '403',
                'kode_subkomponen' => 'A',
                'kode_akun' => null,
                'program_kegiatan' => 'Pelaksanaan Operasional UKPBJ Kementerian Keuangan',
                'pic' => '7',
                'pagu_anggaran' => 39265000,
                'referensi' => '4753EBA403AA',
                'referensi2' => '4753EBA403A',
                'ref_output' => '4753EBA403',
                'len' => 12,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '403',
                'kode_subkomponen' => 'A',
                'kode_akun' => '521211',
                'program_kegiatan' => 'Belanja bahan',
                'pic' => '714',
                'pagu_anggaran' => 19681000,
                'referensi' => '4753EBA403A521211',
                'referensi2' => '4753EBA403A',
                'ref_output' => '4753EBA403',
                'len' => 17,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '403',
                'kode_subkomponen' => 'A',
                'kode_akun' => '524113',
                'program_kegiatan' => 'Belanja Perjalanan Dinas Dalam Kota',
                'pic' => '714',
                'pagu_anggaran' => 19584000,
                'referensi' => '4753EBA403A524113',
                'referensi2' => '4753EBA403A',
                'ref_output' => '4753EBA403',
                'len' => 17,
            ],

            // RO 405
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '405',
                'kode_subkomponen' => null,
                'kode_akun' => null,
                'program_kegiatan' => 'Kerumahtanggaan',
                'pic' => 'SJ.7',
                'pagu_anggaran' => 118793000,
                'referensi' => '4753EBA405',
                'referensi2' => '4753EBA405',
                'ref_output' => '4753EBA405',
                'len' => 10,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '405',
                'kode_subkomponen' => 'C',
                'kode_akun' => null,
                'program_kegiatan' => 'Pelaksanaan Operasional UKPBJ Kementerian Keuangan',
                'pic' => '7',
                'pagu_anggaran' => 118793000,
                'referensi' => '4753EBA405CC',
                'referensi2' => '4753EBA405C',
                'ref_output' => '4753EBA405',
                'len' => 12,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '405',
                'kode_subkomponen' => 'C',
                'kode_akun' => '521211',
                'program_kegiatan' => 'Belanja bahan',
                'pic' => '714',
                'pagu_anggaran' => 14377000,
                'referensi' => '4753EBA405C521211',
                'referensi2' => '4753EBA405C',
                'ref_output' => '4753EBA405',
                'len' => 17,
            ],

            // RO 994
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '994',
                'kode_subkomponen' => null,
                'kode_akun' => null,
                'program_kegiatan' => 'Layanan Perkantoran',
                'pic' => 'SJ.7',
                'pagu_anggaran' => 27332937000,
                'referensi' => '4753EBA994',
                'referensi2' => '4753EBA994',
                'ref_output' => '4753EBA994',
                'len' => 10,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '405',
                'kode_subkomponen' => 'G',
                'kode_akun' => null,
                'program_kegiatan' => 'Operasional dan Pemeliharaan Kantor',
                'pic' => '7',
                'pagu_anggaran' => 27332937000,
                'referensi' => '4753EBA405GG',
                'referensi2' => '4753EBA405G',
                'ref_output' => '4753EBA405',
                'len' => 12,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '405',
                'kode_subkomponen' => 'G',
                'kode_akun' => '521115',
                'program_kegiatan' => 'Honor Operasional satuan kerja',
                'pic' => '714',
                'pagu_anggaran' => 201000000,
                'referensi' => '4753EBA405G521115',
                'referensi2' => '4753EBA405G',
                'ref_output' => '4753EBA405',
                'len' => 17,
            ],
            [
                'kegiatan' => '4753',
                'kro' => 'EBA',
                'ro' => '405',
                'kode_subkomponen' => 'G',
                'kode_akun' => '523113',
                'program_kegiatan' => 'Belanja Asuransi Gedung dan Bangunan',
                'pic' => '714',
                'pagu_anggaran' => 27131937000,
                'referensi' => '4753EBA405G523113',
                'referensi2' => '4753EBA405G',
                'ref_output' => '4753EBA405',
                'len' => 17,
            ],
        ];

        foreach ($data as $item) {
            DB::table('anggaran')->insert(array_merge($item, [
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'tagihan_outstanding' => 0,
                'total_penyerapan' => 0,
                'sisa' => $item['pagu_anggaran'],
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
