<?php

namespace Database\Seeders;

use App\Models\Pegawai;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class PegawaiSeeder extends Seeder
{
    public function run(): void
    {
        $pegawaiData = [
            [
                'nama' => 'Parmono',
                'nama_gelar' => 'Parmono, Ak.',
                'nip' => '197005011991031002',
                'pangkat' => 'Penata Tk.I (III/d)',
                'pendidikan' => 'D4',
                'email_kemenkeu' => 'parmono@kemenkeu.go.id',
                'email_pribadi' => 'abaonom@gmail.com',
                'no_hp' => '085882628763',
                'grading' => 16,
                'jabatan' => 'Kepala Subbagian',
                'jenis_jabatan' => 'Kepala Subbagian',
                'nama_jabatan' => 'Kepala Subbagian Pengembangan Strategi dan Kinerja I',
                'eselon' => 'Eselon IV',
                'jenis_pegawai' => 'Struktural',
                'status' => 'AKTIF',
                'lokasi' => 'PUSAT',
                'bagian' => 'Pengembangan Strategi dan Kinerja',
                'subbagian' => null,
                'jurusan_s1' => 'Akuntansi',
                'tmt_cpns' => Carbon::parse('1991-03-01'),
                'masa_kerja_tahun' => 35,
                'masa_kerja_bulan' => 31,
                'tanggal_lahir' => Carbon::parse('1970-05-01'),
                'usia' => 56,
                'tanggal_pensiun' => Carbon::parse('2028-06-01'),
                'tahun_pensiun' => 2028,
                'proyeksi_kp_1' => '1 October 2010',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama' => 'Kiki Meliza',
                'nama_gelar' => 'Kiki Meliza, S.IP., M.E.',
                'nip' => '198704212010122003',
                'pangkat' => 'Penata Tk.I (III/d)',
                'pendidikan' => 'S2',
                'email_kemenkeu' => 'kiki.meliza@kemenkeu.go.id',
                'email_pribadi' => 'kikimeliza@gmail.com',
                'no_hp' => '085221089521',
                'grading' => 12,
                'jabatan' => 'Pelaksana',
                'jenis_jabatan' => 'Pelaksana',
                'nama_jabatan' => 'Penelaah Teknis Kebijakan Tk.I',
                'eselon' => null,
                'jenis_pegawai' => 'Struktural',
                'status' => 'AKTIF',
                'lokasi' => 'PUSAT',
                'bagian' => 'Pengelolaan Barang Milik Negara',
                'subbagian' => 'Pengelolaan Barang Milik Negara II',
                'jurusan_s1' => 'Perencanaan dan Kebijakan Publik',
                'tmt_cpns' => Carbon::parse('2010-12-01'),
                'masa_kerja_tahun' => 16,
                'masa_kerja_bulan' => 11,
                'tanggal_lahir' => Carbon::parse('1987-04-21'),
                'usia' => 39,
                'tanggal_pensiun' => Carbon::parse('2045-05-01'),
                'tahun_pensiun' => 2045,
                'proyeksi_kp_1' => '1 April 2023',
                'jenis_kelamin' => 'Perempuan',
            ],
            [
                'nama' => 'Sandi Fajar Pratama',
                'nama_gelar' => 'Sandi Fajar Pratama, S.I.Kom., M.Sc.',
                'nip' => '199202182018011002',
                'pangkat' => 'Penata Muda Tk.I (III/b)',
                'pendidikan' => 'S2',
                'email_kemenkeu' => 'sandifp@kemenkeu.go.id',
                'email_pribadi' => 'sandifajarpratama@gmail.com',
                'no_hp' => '081809004025',
                'grading' => 11,
                'jabatan' => 'Pelaksana',
                'jenis_jabatan' => 'Pelaksana',
                'nama_jabatan' => 'Penelaah Teknis Kebijakan Tk.II',
                'eselon' => null,
                'jenis_pegawai' => 'Struktural',
                'status' => 'AKTIF',
                'lokasi' => 'PUSAT',
                'bagian' => 'Pengembangan Strategi dan Kinerja',
                'subbagian' => 'Pengembangan Strategi dan Kinerja I',
                'jurusan_s1' => 'Ilmu Komunikasi',
                'tmt_cpns' => Carbon::parse('2018-01-01'),
                'masa_kerja_tahun' => 8,
                'masa_kerja_bulan' => 4,
                'tanggal_lahir' => Carbon::parse('1992-02-18'),
                'usia' => 34,
                'tanggal_pensiun' => Carbon::parse('2050-03-01'),
                'tahun_pensiun' => 2050,
                'proyeksi_kp_1' => '1 April 2022',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama' => 'Achmad Zaki Rifai',
                'nama_gelar' => 'Achmad Zaki Rifai S.E., M.A.',
                'nip' => '198204212003121001',
                'pangkat' => 'Pembina (IV/a)',
                'pendidikan' => 'S2',
                'email_kemenkeu' => 'zaki@kemenkeu.go.id',
                'email_pribadi' => 'kangmaz@gmail.com',
                'no_hp' => '08561379450',
                'grading' => 15,
                'jabatan' => 'Kepala Subbagian',
                'jenis_jabatan' => 'Kepala Subbagian',
                'nama_jabatan' => 'Kepala Subbagian Pengembangan Strategi dan Kinerja III',
                'eselon' => 'Eselon IV',
                'jenis_pegawai' => 'Struktural',
                'status' => 'AKTIF',
                'lokasi' => 'PUSAT',
                'bagian' => 'Pengembangan Strategi dan Kinerja',
                'subbagian' => null,
                'jurusan_s1' => 'Ekonomi',
                'jurusan_s2' => 'Ilmu Administrasi',
                'tmt_cpns' => Carbon::parse('2003-12-01'),
                'masa_kerja_tahun' => 23,
                'masa_kerja_bulan' => 18,
                'tanggal_lahir' => Carbon::parse('1982-04-21'),
                'usia' => 44,
                'tanggal_pensiun' => Carbon::parse('2040-05-01'),
                'tahun_pensiun' => 2040,
                'proyeksi_kp_1' => '1 Oktober 2023',
                'jenis_kelamin' => 'Laki-laki',
            ],
            [
                'nama' => 'Auliya Putra Azhari',
                'nama_gelar' => 'Auliya Putra Azhari, A. Md. Ak.',
                'nip' => '199609102018011005',
                'pangkat' => 'Pengatur Tk.I (II/d)',
                'pendidikan' => 'D3',
                'email_kemenkeu' => 'auliyaputraazhari@kemenkeu.go.id',
                'email_pribadi' => 'auliyaputraazhari@gmail.com',
                'no_hp' => '082211581510',
                'grading' => 9,
                'jabatan' => 'Pelaksana',
                'jenis_jabatan' => 'Pelaksana',
                'nama_jabatan' => 'Pengolah Data dan Informasi Tk.II',
                'eselon' => null,
                'jenis_pegawai' => 'Struktural',
                'status' => 'AKTIF',
                'lokasi' => 'PUSAT',
                'bagian' => 'Pengembangan Strategi dan Kinerja',
                'subbagian' => 'Tata Usaha Biro',
                'jurusan_s1' => 'Akuntansi',
                'tmt_cpns' => Carbon::parse('2018-01-01'),
                'masa_kerja_tahun' => 8,
                'masa_kerja_bulan' => 4,
                'tanggal_lahir' => Carbon::parse('1996-09-10'),
                'usia' => 30,
                'tanggal_pensiun' => Carbon::parse('2054-10-01'),
                'tahun_pensiun' => 2054,
                'proyeksi_kp_1' => '1 April 2022',
                'jenis_kelamin' => 'Laki-laki',
            ],
        ];

        foreach ($pegawaiData as $data) {
            Pegawai::create($data);
        }

        // Generate additional dummy data
        $bagianList = [
            'Pengembangan Strategi dan Kinerja',
            'Perencanaan Barang Milik Negara',
            'Pengelolaan Barang Milik Negara',
            'Penatausahaan Barang Milik Negara',
            'Manajemen Pengadaan'
        ];

        for ($i = 1; $i <= 45; $i++) {
            Pegawai::create([
                'nama' => 'Pegawai Demo ' . $i,
                'nama_gelar' => 'Pegawai Demo ' . $i . ', S.E.',
                'nip' => '19' . str_pad(80 + $i, 2, '0', STR_PAD_LEFT) . '0101' . (2000 + $i) . '121001',
                'pangkat' => 'Penata (III/c)',
                'pendidikan' => 'S1',
                'email_kemenkeu' => 'pegawai' . $i . '@kemenkeu.go.id',
                'no_hp' => '0812' . str_pad($i, 8, '0', STR_PAD_LEFT),
                'grading' => rand(8, 14),
                'jabatan' => 'Pelaksana',
                'jenis_jabatan' => 'Pelaksana',
                'nama_jabatan' => 'Penelaah Teknis Kebijakan',
                'status' => rand(0, 10) > 1 ? 'AKTIF' : 'CLTN',
                'lokasi' => 'PUSAT',
                'bagian' => $bagianList[array_rand($bagianList)],
                'jurusan_s1' => ['Ekonomi', 'Akuntansi', 'Manajemen', 'Ilmu Administrasi'][array_rand(['Ekonomi', 'Akuntansi', 'Manajemen', 'Ilmu Administrasi'])],
                'tmt_cpns' => Carbon::parse((2000 + $i) . '-01-01'),
                'masa_kerja_tahun' => rand(5, 20),
                'tanggal_lahir' => Carbon::parse((1980 + $i) . '-01-01'),
                'usia' => 2026 - (1980 + $i),
                'tanggal_pensiun' => Carbon::parse((2038 + $i) . '-01-01'),
                'tahun_pensiun' => 2038 + $i,
                'jenis_kelamin' => rand(0, 1) ? 'Laki-laki' : 'Perempuan',
            ]);
        }
    }
}
